### ISSUE TITLE
boostrap-sass RightParenthesis is expected error

### ISSUE THREAD

**Issue by stelro** [ueno-llc/starter-kit-universally#37]
Hello, I am having some issue when I am importing bootstrap-sass to the project tree. 
I Have installed boostrap and boostrap-sass and all necessery loaders, but I got those errors 

> ERROR in ./~/css-loader?{"sourceMap":true,"modules":true,"importLoaders":1,"localIdentName":"[name]_[local]_[hash:base64:5]"}!./~/postcss-loader!./~/sass-loader/lib/loader.js!./styles/main.scss
> Module build failed: RightParenthesis is expected (246:21)
> 
>   244 | @font-face {
>   245 |   font-family: 'Glyphicons Halflings';
> > 246 |   src: url(font-path("bootstrap/glyphicons-halflings-regular.eot"));
>       |                     ^
>   247 |   src: url(font-path("bootstrap/glyphicons-halflings-regular.eot?#iefix")) format("embedded-opentype"), url(font-path("bootstrap/glyphicons-halflings-regular.woff2")) format("woff2"), url(font-path("bootstrap/glyphicons-halflings-regular.woff")) format("woff"), url(font-path("bootstrap/glyphicons-halflings-regular.ttf")) format("truetype"), url(font-path("bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular")) format("svg"); }
>   248 | 
> 
>  @ ./~/style-loader!./~/css-loader?{"sourceMap":true,"modules":true,"importLoaders":1,"localIdentName":"[name]_[local]_[hash:base64:5]"}!./~/postcss-loader!./~/sass-loader/lib/loader.js!./styles/main.scss 4:14-268 18:2-22:4 19:20-274
>  @ ./styles/main.scss

How can i solve this ?

**Comment by birkir** [comment]
Sorry, we're using css modules here, so importing arbitrary scss libraries from node_modules is not going to work. (They won't get processed by webpack).

We already have a rule in place (for our ueno-ui module) that can process css files from node_modules.

To point you in the right direction, you copy and paste that rule, change the extension to `.scss` and add the scss plugin.

https://github.com/ueno-llc/starter-kit-universally/blob/development/internal/webpack/configFactory.js#L529-L538

I am closing because we won't support it for now. Feel free to re-open if you think otherwise.
