### ISSUE TITLE
Access Enviroment Variables from Heroku

### ISSUE THREAD

**Issue by stelro** [ueno-llc/starter-kit-universally#85]
How can I access env variables from Heorku and use it in my stores? and separate the project to production and stagging?

**Comment by baldurh** [comment]
Hi @stelro!

To access your env variables (Heroku or not) you use the `utils/config` module. You can see an example of it in the [Home Route](https://github.com/ueno-llc/starter-kit-universally/blob/5ffa1f07804b3d29120dd80e109bd7002ed6fbef/shared/routes/home/Home.js)

To get your env variables exposed to the app you need to define them in [values.js](https://github.com/ueno-llc/starter-kit-universally/blob/5ffa1f07804b3d29120dd80e109bd7002ed6fbef/config/values.js)

If they need to be exposed to the client bundle, you need to add them to the `clientConfigFilter` inside the `values` object in `values.js`.

Just be careful not to add sensitive keys to `clientConfigFilter` because it will be exposed in JS bundle loaded by clients.

If you need a separate staging environment you can use the already defined `NODE_ENV` env variable. Just set it to `"staging"` in your environment use it to modify your code for your needs.

Hope this helps 😊
